Lint/UnusedBlockArgument:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/PredicateName:
  Enabled: false

Style/RegexpLiteral:
  MaxSlashes: 0

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingComma:
  Enabled: false
