Lint/UnusedMethodArgument:
  Enabled: false

Metrics/LineLength:
  Max: 104

Style/Documentation:
  Enabled: false

Style/RegexpLiteral:
  MaxSlashes: 0

Style/StringLiterals:
  EnforcedStyle: double_quotes
